openapi: 3.0.0
info:
  title: APIs OpenData do Open Banking Brasil
  description: As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.
  version: 1.0.0
  contact:
    email: "apiteam@swagger.io"
tags:
  - name: "Channels"
    description: "Operações para listagem de canais de atendimentos"
servers:
  - url: http://api.banco.com.br/open-banking/channels/v1
paths:
  /banking-agents:
    get:
      tags:
        - "Channels"
      summary: Obtém a lista de correspondentes bancários da instituição financeira.
      description: "Método para obter a lista de correspondentes bancários da instituição financeira."
      operationId: "getBankingAgents"
      responses:
        '200':
          description: Lista de correspondentes bancários obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBankingAgentsList'
  /branches:
    get:
      tags:
        - "Channels"
      summary: Obtém a lista de dependências próprias da instituição financeira.
      description: "Método para obter a lista de dependências próprias da instituição financeira."
      operationId: "getBranches"
      responses:
        '200':
          description: Lista de dependências próprias obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBranchesList'
  /electronic-channels:
    get:
      tags:
        - "Channels"
      summary: Obtém a lista de canais eletrônicos de atendimento da instituição financeira.
      description: "Método para obter a lista de canais eletrônicos de atendimento da instituição financeira."
      operationId: "getElectronicChannels"
      responses:
        '200':
          description: Lista de canais eletrônicos de atendimento obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseElectronicChannelsList'
  /phone-channels:
    get:
      tags:
        - "Channels"
      summary: "Obtém a lista de canais telefônicos de atendimento da instituição financeira."
      description: "Método para obter a lista de canais telefônicos de atendimento da instituição financeira."
      operationId: "getPhoneChannels"
      responses:
        '200':
          description: Lista de canais telefônicos de atendimento obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsePhoneChannelsList'
  /shared-automated-teller-machines:
    get:
      tags:
        - "Channels"
      summary: "Obtém a lista de terminais compartilhados de autoatendimento."
      description: "Método para obter a lista de terminais compartilhados de autoatendimento da instituição financeira."
      operationId: "getSharedAutomatedTellerMachines"
      responses:
        '200':
          description: Lista de terminais compartilhados de autoatendimento obtida com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSharedAutomatedTellerMachinesList'
components:
  schemas:
    ResponseBankingAgentsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/BankingAgentsBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
    BankingAgentsBrand:
      type: object
      required:
        - name
        - companies
      allOf:
        - $ref: '#/components/schemas/Brand'
      properties:
        companies:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgentsCompanies'
          description: Lista de instituições pertencentes à marca
    BankingAgentsCompanies:
      type: object
      required:
        - name
        - cnpjNumber
        - contractors
      properties:
        name:
          type: string
          maxLength: 80
          description: Nome da Instituição, pertencente à Marca, responsável pela Dependência. p. ex. 'Empresa da Organização A'.
        contractors:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgentsContractor'
          description: Lista de contratantes
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    BankingAgentsContractor:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        bankingAgents:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgent'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseBranchesList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/BranchesBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          brand:
            name: Organização A
            companies:
              - name: Empresa A1
                cnpjNumber: '45086338000178'
                urlComplementaryList: 'https://empresaa1.com/branches-banking'
                branches:
                  - identification:
                      type: 'AGENCIA'
                      code: '0001'
                      checkDigit: '9'
                      name: 'Marília'
                    postalAddress:
                      address: 'Av Naburo Ykesaki, 1270'
                      districtName: 'Centro'
                      townName: 'Marília'
                      countrySubDivision: 'SP'
                      postCode: '17500-001'
                    availability:
                      standards:
                        - weekday: SEGUNDA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: TERCA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUARTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: QUINTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                        - weekday: SEXTA_FEIRA
                          openingTime: '10:00:57Z'
                          closingTime: '16:00:57Z'
                      exception: 'Exceto feriados municipais, estaduais e nacionais'
                      allowPublicAccess: true
                    phones:
                      - type: FIXO
                        countryCallingCode: '55'
                        areaCode: '14'
                        number: '35721199'
                      - type: MOVEL
                        countryCallingCode: '55'
                        areaCode: '14'
                        number: '997865532'
                    service:
                      codes:
                        - ABERTURA_CONTAS
                        - RECEBIMENTOS_PAGAMENTOS_TRANSFERENCIAS_ELETRONICAS
                        - RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
                        - OPERACOES_CREDITO
                        - CARTAO_CREDITO
                        - OPERACOES_CAMBIO
                        - INVESTIMENTOS
                        - SEGUROS
                        - OUTROS
                      additionalInfo: "Renegociação, Previdência Privada"
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/branches'
          first: 'https://api.banco.com.br/open-banking/channels/v1/branches'
          prev: "null"
          next: "null"
          last: 'https://api.banco.com.br/open-banking/channels/v1/branches'
        meta:
          totalRecords: 1
          totalPages: 1
    BranchesBrand:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          description: Nome da marca selecionada pela Organização proprietária da dependência (titular).
        companies:
          type: array
          items:
            $ref: '#/components/schemas/BranchesCompanies'
          description: Lista de contratantes
    BranchesCompanies:
      type: object
      required:
        - name
        - cnpjNumber
      properties:
        name:
          type: string
        cnpjNumber:
          type: string
          minLength: 14
          maxLength: 14
          pattern: '^(\d{14})$'
          description: |
            Número completo do CNPJ da instituição responsável pela dependência - o CNPJ corresponde ao número de inscrição no Cadastro de Pessoa Jurídica.
            Deve-se ter apenas os números do CNPJ, sem máscara
          example: '45086338000178'
        urlComplementaryList:
          type: string
          maxLength: 1024
          example: 'https://example.com/mobile-banking'
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseElectronicChannelsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/ElectronicChannelsBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          brand:
            name: 'Organização A'
            companies:
              - name: 'Empresa A1'
                cnpjNumber: '45086338000178'
                urlComplementaryList: 'https://empresaa1.com/branches-banking'
                electronicChannels:
                  - identification:
                      type: 'INTERNET_BANKING'
                      additionalInfo: 'NA'
                      url: 'https://empresaa1.com/internet-banking'
                    services:
                      - name: "ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA"
                        code: "ABRE_CONTA_DEPOSITO_OU_PRE_PAGA"
                        additionalInfo: 'NA'
                      - name: "SEGUROS"
                        code: "SEGUROS"
                        additionalInfo: 'NA'
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
          first: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
          prev: "null"
          next: "null"
          last: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
        meta:
          totalRecords: 1
          totalPages: 1
    ElectronicChannelsBrand:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          description: Nome da marca selecionada pela Organização proprietária da dependência (titular).
          example: "Marca A"
          maxLength: 80
        companies:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannelsCompanies'
          minItems: 1
          description: Lista de instituições pertencentes à marca
    ElectronicChannelsCompanies:
      type: object
      required:
        - name
        - electronicChannels
        - cnpjNumber
      properties:
        name:
          type: string
          description: Nome da marca selecionada pela Organização proprietária da dependência (titular).
          example: "Empresa da Marca A"
        urlComplementaryList:
          type: string
          maxLength: 1024
          example: "https://example.com/mobile-banking"
        electronicChannels:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannel'
          minItems: 1
          maxItems: 4
          description: Lista  de canais de atendimento eltrônico
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    BankingAgent:
      type: object
      required:
        - identification
        - postalAddresses
        - services
      properties:
        identification:
          $ref: '#/components/schemas/BankingAgentIdentification'
        postalAddresses:
          type: array
          required:
            - districtName
            - townName
            - countrySubDivision
            - postCode
            - address
          items:
            $ref: '#/components/schemas/PostalAddress'
        services:
          $ref: '#/components/schemas/BankingAgentServices'
    BankingAgentIdentification:
      type: object
      properties:
        corporationName:
          type: string
          maxLength: 100
        groupName:
          type: string
          maxLength: 100
      allOf:
        - $ref: '#/components/schemas/CNPJ'
      required:
        - cnpjNumber
        - corporationName
    BankingAgentServices:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            enum:
              - ABERTURA_CONTAS
              - RECEBIMENTOS_PAGAMENTOS_TRANSFERENCIAS_ELETRONICAS
              - RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
              - ORDEM_PAGAMENTO
              - OPERACOES_CREDITO
              - RECEBIMENTOS_PAGAMENTOS_LETRAS_CAMBIO
              - CARTAO_CREDITO
              - OPERACOES_CAMBIO
            description: >
              Serviços oferecidos pelo correspondente bancário
              * `ABERTURA_CONTAS` - Recepção e encaminhamento de propostas de abertura de contas
              * `RECEBIMENTOS_PAGAMENTOS_TRANSFERENCIAS_ELETRONICAS` - Realização de recebimentos, pagamentos e transferências eletrônicas
              * `RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA` - Recebimentos e pagamentos de qualquer natureza
              * `ORDEM_PAGAMENTO` - Execução ativa e passiva de ordens de pagamento
              * `OPERACOES_CREDITO` - Recepção e encaminhamento de propostas de operações de crédito e de arrendamento mercantil
              * `RECEBIMENTOS_PAGAMENTOS_LETRAS_CAMBIO` - Recebimento e pagamentos relacionados a letras de câmbio de aceite da instituição
              * `CARTAO_CREDITO` - Recepção e encaminhamento de propostas de fornecimento de cartões de crédito
              * `OPERACOES_CAMBIO` - Realização de operações de câmbio
          description: Serviços oferecidos pelo canal eletrônico
        additionalInfo:
          type: string
          maxLength: 2000
          description: Campo aberto para detalhamento
      required:
        - codes
    Branch:
      type: object
      required:
        - identification
        - postalAddress
        - availability
        - service
      properties:
        identification:
          $ref: '#/components/schemas/BranchIdentification'
        postalAddresses:
          $ref: '#/components/schemas/BranchPostalAddress'
        availability:
          $ref: '#/components/schemas/BranchAvailability'
        phones:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
        service:
          $ref: '#/components/schemas/BranchServices'
    BranchPostalAddress:
      type: object
      required:
        - districtName
        - townName
        - countrySubDivision
        - postCode
        - address
      allOf:
        - $ref: '#/components/schemas/PostalAddress'
    BranchIdentification:
      type: object
      properties:
        type:
          type: string
          enum:
            - AGENCIA
            - POSTO_ATENDIMENTO
            - POSTO_ATENDIMENTO_ELETRONICO
          description: >
            Tipo da dependência, segundo a regulamentação do Bacen,  na Resolução Nº 4072, de 26 de abril de 2012:
            Agência é a dependência destinada ao atendimento aos clientes e ao público em geral no exercício de atividades da instituição, não podendo ser móvel ou transitória;
              Dependência de instituições financeiras e demais instituições, autorizadas a funcionar pelo Banco Central do Brasil, destinada à prática das atividades para as quais a instituição esteja regularmente habilitada.
            Posto de Atendimento é a dependência subordinada a agência  ou à sede da instituição financeira, destinada ao atendimento ao público no exercício de uma ou mais de suas atividades, podendo ser fixo ou móvel. Segundo Art.15. Os Postos de Atendimento Bancário (PAB), Postos Avançados de Atendimento (PAA), Postos de Atendimento Transitórios (PAT), Postos de Compra de Ouro (PCO), Postos de Atendimento Cooperativo (PAC), Postos de Atendimento de Microcrédito (PAM), Postos Bancários de Arrecadação e Pagamento (PAP) e os Postos de Câmbio atualmente em funcionamento serão considerados PA.
            Posto de Atendimento Eletrônico é a dependência constituída por um ou mais terminais de autoatendimento, subordinada a agência ou à sede da instituição, destinada à prestação de serviços por meio eletrônico, podendo ser fixo ou móvel, permanente ou transitório
        code:
          type: string
          maxLength: 4
          pattern: ^\d{4}$
        checkDigit:
          type: string
          maxLength: 1
          pattern: ^\d{1}$
        name:
          type: string
          maxLength: 100
      required:
        - type
        - code
        - checkDigit
        - name
    BranchAvailability:
      type: object
      properties:
        standards:
          type: array
          items:
            properties:
              weekday:
                type: string
                enum:
                  - DOMINGO
                  - SEGUNDA_FEIRA
                  - TERCA_FEIRA
                  - QUARTA_FEIRA
                  - QUINTA_FEIRA
                  - SEXTA_FEIRA
                  - SABADO
                description: Dia da semana de abertura da dependência bancária
              openingTime:
                type: string
                description: Horário de abertura da dependência bancária (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$
              closingTime:
                type: string
                description: Horário de fechamento da dependência bancária (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$
            required:
              - weekday
              - openingTime
              - closingTime
        exception:
          type: string
          maxLength: 2000
        allowPublicAccess:
          type: boolean
      required:
        - standards
        - exception
        - allowPublicAccess
    BranchServices:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            enum:
              - ABERTURA_CONTAS
              - RECEBIMENTOS_PAGAMENTOS_TRANSFERENCIAS_ELETRONICAS
              - RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
              - OPERACOES_CREDITO
              - CARTAO_CREDITO
              - OPERACOES_CAMBIO
              - INVESTIMENTOS
              - SEGUROS
              - OUTROS
          description: >
            Serviços prestados pela dependência consultada:
            * Abertura de contas
            * Recebimentos, pagamentos e transferências eletrônicas
            * Recebimentos e pagamentos de qualquer natureza
            * Operações de crédito
            * Cartão de crédito
            * Operações de câmbio
            * Investimentos
            * Seguros
            * Outros
        additionalInfo:
          type: string
          description: Campo de texto livre para descrever mais sobre os serviços
          maxLength: 2000
      required:
        - codes
    ElectronicChannel:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/ElectronicChannelIdentification'
        services:
          type: array
          items:
            $ref: '#/components/schemas/ElectronicChannelService'
          minItems: 1
          maxItems: 20
          description: "Traz a relação de serviços disponbilizados pelo Canal de Atendimento"
      required:
        - identification
        - services
    ElectronicChannelIdentification:
      type: object
      required:
        - type
        - url
      properties:
        type:
          type: string
          enum:
            - INTERNET_BANKING
            - MOBILE_BANKING
            - SAC
            - OUVIDORIA
            - CHAT
            - OUTROS
          description: "Tipo de canal de atendimento eletrônico"
          example: "CHAT"
        additionalInfo:
          type: string
          maxLength: 256
        url:
          type: string
          maxLength: 1024
          example: "https://example.com/mobile-banking"
    ElectronicChannelService:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
          enum:
            - ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA
            - SAQUE_MOEDA_EM_ESPECIE
            - RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
            - TRANSFERENCIAS_ELETRONICAS_VISANDO_MOVIMENTACAO_CONTAS_DEPOSITOS_OU_PAGAMENTO_TITULARIDADE_CLIENTES
            - CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_CONTAS_PAGAMENTOS
            - APLICACOES_RESGATES_INVESTIMENTOS
            - EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGAMENTO_SOLICITACAO_CLIENTES_USUARIOS
            - DEPOSITOS_MOEDA_ESPECIE_CHEQUE
            - OPERACOES_CREDITO_BEM_COMO_OUTROS_SERVICOS_PRESTADOS_ACOMPANHAMENTO_OPERACAO
            - CARTAO_CREDITO
            - SEGUROS
            - OPERACOES_ARRENDAMENTO_MERCANTIL
            - ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            - COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE
            - COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_BEM_COMO_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            - COMPRA_VENDA_OURO
            - OUTROS_PRODUTOS_SERVICOS
            - CANCELAMENTO
            - INFORMACOES
            - RECLAMACOES
          description: "Nome dos Serviços efetivamente prestados pelo Canal de Atendimento"
          example: "ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA"
        code:
          type: string
          enum:
            - ABRE_CONTA_DEPOSITO_OU_PRE_PAGA
            - SAQUE_MOEDA_ESPECIE
            - RECEBE_PAGA_QUALQUER_NATUREZA
            - TRANSFERENCIAS_ELETRONICAS_MOVIMENTA_CONTAS_DEPOSITOS_OU_PAGTO_TITULARES_CLIENTES
            - CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_PAGTOS
            - APLICA_RESGATA_INVESTIMENTOS
            - EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGTO
            - DEPOSITO_MOEDA_ESPECIE_CHEQUE
            - OPERA_CREDITO_OUTROS_SERVICOS_ACOMPANHA_OPERACAO
            - CARTAO_CREDITO
            - SEGUROS
            - OPERA_ARRENDAMENTO_MERCANTIL
            - ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            - COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE
            - COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            - COMPRA_VENDA_OURO
            - OUTROS_PRODUTOS_SERVICOS
            - CANCELAMENTO
            - INFORMACOES
            - RECLAMACOES
          description: "Código dos Serviços efetivamente prestados pelo Canal de Atendimento"
          example: "ABRE_CONTA_DEPOSITO_OU_PRE_PAGA"
        additionalInfo:
          type: string
          maxLength: 2000
          description: "Texto livre para complementar informação relativa ao Serviço disponível, quando for selecionada a opção p preenchida a opção 'OUTROS_PRODUTOS_SERVICOS'"
          example: ""
    Phone:
      type: object
      required:
        - countryCallingCode
        - areaCode
        - number
      properties:
        type:
          type: string
          enum:
            - FIXO
            - MOVEL
          example: "FIXO"
          description: "Identificação do Tipo de telefone da dependência. p.ex.FIXO, MOVEL."
        countryCallingCode:
          type: string
          maxLength: 2
          pattern: ^\d{2}$
          example: "55"
          description: "Número de DDI (Discagem Direta Internacional) para  telefone de acesso ao Canal - se houver. p.ex. '55'"
        areaCode:
          type: string
          maxLength: 2
          pattern: ^\d{2}$
          example: "19"
          description: "Número de DDD (Discagem Direta à Distância) do telefone da dependência - se houver. p.ex. '19'"
        number:
          type: string
          maxLength: 11
          pattern: '^([0-9]{8,11})$'
          example: "35721199"
          description: "Número de telefone da dependência - se houver"
    PostalAddress:
      type: object
      properties:
        address:
          type: string
          description: "Deverá trazer toda a informação referente ao endereço da dependência informada: Tipo de logradouro + Nome do logradouro + Número do Logradouro (se não existir usar ' s/n') + complemento (se houver), como, p.ex.: 'R Diamatina, 59, bloco 35, fundos' 'Praça da Boa Vontade s/n'"
          maxLength: 150
          pattern: \w*\W*
          example: 'Av Naburo Ykesaki, 1270'
        additionalInfo:
          type: string
          description: "Complemento"
          maxLength: 30
          pattern: \w*\W*
          example: 'Fundos'
        districtName:
          type: string
          description: "Bairro é uma comunidade ou região localizada em uma cidade ou município de acordo com as suas subdivisões geográficas. p.ex: 'Paraíso'"
          maxLength: 50
          pattern: \w*\W*
          example: 'Centro'
        townName:
          type: string
          description: "Localidade: O nome da localidade corresponde à designação da cidade ou município no qual o endereço está localizado. p.ex. 'São Paulo'"
          maxLength: 50
          pattern: \w*\W*
          example: 'Marília'
        ibgeCode:
          type: string
          description: "Código IBGE do município"
          maxLength: 7
          pattern: \d{7}|^NA$
          example: '3515890'
        countrySubDivision:
          type: string
          description: "Enumeração referente a cada sigla da unidade da federação que identifica o estado ou o distrito federal, no qual o endereço está localizado. p.ex. 'AC'. São consideradas apenas as siglas para os estados brasileiros"
          enum:
            - AC
            - AL
            - AP
            - AM
            - BA
            - CE
            - DF
            - ES
            - GO
            - MA
            - MT
            - MS
            - MG
            - PA
            - PB
            - PR
            - PE
            - PI
            - RJ
            - RN
            - RS
            - RO
            - RR
            - SC
            - SP
            - SE
            - TO
          example: 'SP'
        postCode:
          type: string
          description: "Código de Endereçamento Postal"
          pattern: (\d{8})
          maxLength: 8
          example: '17500001'
        country:
          type: string
          description: "Nome do país"
          maxLength: 80
          pattern: \w*\W*
          example: 'Brasil'
        countryCode:
          type: string
          description: "Código do país"
          example: 'BRA'
        geographicCoordinates:
          $ref: '#/components/schemas/GeographicCoordinates'
    ResponseSharedAutomatedTellerMachinesList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          properties:
            brand:
              $ref: '#/components/schemas/SharedAutomatedTellerMachinesBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
    SharedAutomatedTellerMachinesBrand:
      type: object
      allOf:
        - $ref: '#/components/schemas/Brand'
      properties:
        companies:
          type: array
          items:
            $ref: '#/components/schemas/SharedAutomatedTellerMachinesCompanies'
          description: Lista de instituições pertencentes à marca
    SharedAutomatedTellerMachinesCompanies:
      properties:
        sharedAutomatedTellerMachines:
          type: array
          items:
            $ref: '#/components/schemas/SharedAutomatedTellerMachines'
      allOf:
        - $ref: '#/components/schemas/SharedAutomatedTellerMachinesCompany'
    SharedAutomatedTellerMachines:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/SharedAutomatedTellerMachinesIdentification'
        address:
          $ref: '#/components/schemas/SharedAutomatedTellerMachinesPostalAddress'
        availability:
          $ref: '#/components/schemas/SharedAutomatedTellerMachinesAvailability'
        services:
          type: array
          items:
            $ref: '#/components/schemas/SharedAutomatedTellerMachinesServices'
    SharedAutomatedTellerMachinesServices:
      type: object
      properties:
        name:
          type: string
          enum:
            - ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA
            - SAQUE_MOEDA_EM_ESPECIE
            - RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
            - TRANSFERENCIAS_ELETRONICAS_VISANDO_MOVIMENTACAO
            - CONTAS_DEPOSITOS_OU_PAGAMENTO_TITULARIDADE_CLIENTES
            - CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_E_CONTAS
            - PAGAMENTOS
            - APLICACOES_RESGATES_INVESTIMENTOS
            - EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGAMENTO_SOLICITACAO
            - CLIENTES_USUARIOS
            - DEPOSITOS_MOEDA_ESPECIE_CHEQUE
            - OPERACOES_CREDITO_BEM_COMO_OUTROS_SERVICOS_PRESTADOS_ACOMPANHAMENTO_OPERACAO
            - CARTAO_CREDITO
            - SEGUROS
            - OPERACOES_ARRENDAMENTO_MERCANTIL
            - ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            - COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE
            - COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_BEM_COMO_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            - COMPRA_VENDA_OURO
            - OUTROS_PRODUTOS_SERVICOS
            - CANCELAMENTO
            - INFORMACOES
            - RECLAMACOES
          description: "Nome dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado"
          example: OUTROS_PRODUTOS_SERVICOS
        code:
          type: string
          enum:
            - ABRE_CONTA_DEPOSITO_OU_PRE_PAGA
            - SAQUE_MOEDA_ESPECIE
            - RECEBE_PAGA_QUALQUER_NATUREZA
            - TRANSFERENCIAS_ELETRONICAS_MOVIMENTA_CONTAS_DEPOSITOS_OU_PAGA_TITULARES_CLIENTES
            - CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS
            - PAGAMENTOS
            - APLICA_RESGATA_INVESTIMENTOS
            - EXECUTA_ATIVA_PASSIVA_ORDENS_PAGAMENTO
            - DEPOSITA_MOEDA_ESPECIE_CHEQUE
            - OPERA_CREDITO_OUTROS_SERVICOS_ACOMPANHA_OPERACAO
            - CARTAO_CREDITO
            - SEGUROS
            - OPERA_ARRENDAMENTO_MERCANTIL
            - ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            - COMPRA_VENDE_MOEDA_ESTRANGEIRA_ESPECIE
            - COMPRA_VENDE_CHEQUE_CHEQUE_VIAGEM_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            - COMPRA_VENDE_OURO
            - OUTROS_PRODUTOS_SERVICOS
            - CANCELAMENTO
            - INFORMACOES
            - RECLAMACOES
          description: "Código dos Serviços efetivamente prestados pelo Terminal de Autoatendimento Compartilhado informado"
          example: OUTROS_PRODUTOS_SERVICOS
        additionalInfo:
          type: string
          maxLength: 2000
          pattern: \w*\W*
          description: Texto livre para complementar informação relativa ao Serviço disponível, quando for preenchida a opção 'OUTROS_PRODUTOS_SERVICOS'
          example: "Serviços complementares de atendimento via terminais de autoatendimento."
    SharedAutomatedTellerMachinesIdentification:
      type: object
      properties:
        ownerName:
          type: string
          maxLength: 100
          pattern: \w*\W*
          description: "Nome do proprietário do terminal de Autoatendimento Compartilhado"
          example: "João da Silva Santos"
    ####################
    ## Phone ElectronicChannels ##
    ####################
    #### ResponsePhoneChannelsList ####
    ResponsePhoneChannelsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - brand
          properties:
            brand:
              $ref: '#/components/schemas/PhoneChannelsBrand'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          brand:
            name: 'Organização A'
            companies:
              - name: 'Empresa A1'
                cnpjNumber: '45086338000178'
                urlComplementaryList: 'https://empresaa1.com/branches-banking'
                phoneChannels:
                  - identification:
                      type: 'CENTRAL_TELEFONICA'
                      additionalInfo: 'NA'
                      phones:
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '3572-1199'
                          additionalInfo: 'NA'
                        - countryCallingCode: '55'
                          areaCode: '14'
                          number: '99786-5532'
                          additionalInfo: 'NA'
                    services:
                      - name: 'ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA'
                        code: 'ABRE_CONTA_DEPOSITO_OU_PRE_PAGA'
                        additionalInfo: 'NA'
                      - name: 'RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA'
                        code: 'RECEBE_PAGA_QUALQUER_NATUREZA'
                        additionalInfo: 'NA'
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/phone-channels'
          first: 'https://api.banco.com.br/open-banking/channels/v1/phone-channels'
          prev: "null"
          next: "null"
          last: 'https://api.banco.com.br/open-banking/channels/v1/phone-channels'
        meta:
          totalRecords: 1
          totalPages: 1
    #### PhoneChannelsBrand ####
    PhoneChannelsBrand:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          pattern: '\w*\W*'
          maxLength: 30
          description: "Nome da Marca reportada pelo participante do Open Banking. O conceito a que se refere a 'marca' utilizada está em definição pelos participantes."
          example: "Marca A"
        companies:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannelsCompanies'
          minItems: 1
          description: Lista de instituições pertencentes à marca
    #### PhoneChannelsCompanies ####
    PhoneChannelsCompanies:
      type: object
      required:
        - name
        - phoneChannels
        - cnpjNumber
      properties:
        name:
          type: string
          description: "Nome da Instituição, pertencente à organização, responsável pelo Canal Telefônico."
          example: "Empresa da Marca A"
        urlComplementaryList:
          type: string
          maxLength: 1024
          example: "https://example.com/mobile-banking"
        phoneChannels:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannel'
          minItems: 1
          maxItems: 4
          description: Lista  de canais de atendimento telefônico
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    #### PhoneChannel ####
    PhoneChannel:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/PhoneChannelIdentification'
        services:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannelService'
          minItems: 1
          maxItems: 20
          description: Traz a relação de serviços disponbilizados pelo Canal de Atendimento
      required:
        - identification
        - services
    #### PhoneChannelIdentification ####
    PhoneChannelIdentification:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - CENTRAL_TELEFONICA
            - SAC
            - OUVIDORIA
            - OUTROS
          description: "Tipo de canal telefônico de atendimento"
          example: "OUVIDORIA"
        additionalInfo:
          type: string
          maxLength: 256
          description: "Campo de texto livre para descrever quando o tipo de canal de atendimento for Outros"
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneChannelPhone'
          minItems: 1
          description: "Lista de telefones do Canal de Atendimento"
    #### PhoneChannelPhone ####
    PhoneChannelPhone:
      type: object
      required:
        - countryCallingCode
        - areaCode
        - number
      properties:
        countryCallingCode:
          type: string
          maxLength: 2
          pattern: ^\d{2}$
          example: "55"
          description: "Número de DDI (Discagem Direta Internacional) para  telefone de acesso ao Canal - se houver."
        areaCode:
          type: string
          maxLength: 2
          pattern: ^\d{2}$
          example: "19"
          description: "Número de DDD (Discagem Direta à Distância) para  telefone de acesso ao Canal - se houver."
        number:
          type: string
          maxLength: 13
          pattern: ^([0-9]{4,5})-([0-9]{4,7})$
          example: "0800-7787788"
          description: "Número de telefone de acesso ao canal. "
        additionalInfo:
          type: string
          maxLength: 100
          example: "Mensagem complementar necessária para o agrupamento da identificação do telefone."
    #### PhoneChannelService ####
    PhoneChannelService:
      type: object
      required:
        - name
        - code
      properties:
        name: 
          type: string
          enum:
            - ABERTURA_CONTAS_DEPOSITOS_OU_PAGAMENTO_PRE_PAGA
            - SAQUE_MOEDA_EM_ESPECIE
            - RECEBIMENTOS_PAGAMENTOS_QUALQUER_NATUREZA
            - TRANSFERENCIAS_ELETRONICAS_VISANDO_MOVIMENTACAO_CONTAS_DEPOSITOS_OU_PAGAMENTO_TITULARIDADE_CLIENTES
            - CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_CONTAS_PAGAMENTOS
            - APLICACOES_RESGATES_INVESTIMENTOS
            - EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGAMENTO_SOLICITACAO_CLIENTES_USUARIOS
            - DEPOSITOS_MOEDA_ESPECIE_CHEQUE
            - OPERACOES_CREDITO_BEM_COMO_OUTROS_SERVICOS_PRESTADOS_ACOMPANHAMENTO_OPERACAO
            - CARTAO_CREDITO
            - SEGUROS
            - OPERACOES_ARRENDAMENTO_MERCANTIL
            - ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            - COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE
            - COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_BEM_COMO_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            - COMPRA_VENDA_OURO
            - OUTROS_PRODUTOS_SERVICOS
            - CANCELAMENTO
            - INFORMACOES
            - RECLAMACOES
          description: "Nome dos Serviços efetivamente prestados pelo Canal de Atendimento"
        code:
          type: string
          enum:
            - ABRE_CONTA_DEPOSITO_OU_PRE_PAGA
            - SAQUE_MOEDA_ESPECIE
            - RECEBE_PAGA_QUALQUER_NATUREZA
            - TRANSFERENCIAS_ELETRONICAS_MOVIMENTA_CONTAS_DEPOSITOS_OU_PAGTO_TITULARES_CLIENTES
            - CONSULTA_SALDOS_EXTRATOS_CONTAS_DEPOSITOS_PAGTOS
            - APLICA_RESGATA_INVESTIMENTOS
            - EXECUCAO_ATIVA_PASSIVA_ORDENS_PAGTO
            - DEPOSITO_MOEDA_ESPECIE_CHEQUE
            - OPERA_CREDITO_OUTROS_SERVICOS_ACOMPANHA_OPERACAO
            - CARTAO_CREDITO
            - SEGUROS
            - OPERA_ARRENDAMENTO_MERCANTIL
            - ABERTURA_CONTA_PAGAMENTO_POS_PAGA
            - COMPRA_VENDA_MOEDA_ESTRANGEIRA_ESPECIE
            - COMPRA_VENDA_CHEQUE_CHEQUE_VIAGEM_CARGA_MOEDA_ESTRANGEIRA_CARTAO_PRE_PAGO
            - COMPRA_VENDA_OURO
            - OUTROS_PRODUTOS_SERVICOS
            - CANCELAMENTO
            - INFORMACOES
            - RECLAMACOES
          description: "Código dos Serviços efetivamente prestados pelo Canal de Atendimento"
        additionalInfo:
          type: string
          maxLength: 2000
          description: "Texto livre para complementar informação relativa ao Serviço disponível, quando for selecionada a opção p preenchida a opção 'OUTROS_PRODUTOS_SERVICOS'"
          example: ""
    GeographicCoordinates:
      type: object
      properties:
        latitude:
          description: Informação da latitude referente a geolocalização informada.
          type: string
          pattern: ^-?\d{1,2}\.\d{1,9}$|^NA$
          example: '-90.8365180'
        longitude:
          description: Informação da longitude referente a geolocalização informada.
          type: string
          pattern: ^-?\d{1,3}\.\d{1,8}$|^NA$
          example: '-180.836519'
    Availability:
      type: object
      properties:
        standards:
          type: array
          items:
            properties:
              weekday:
                type: string
                enum:
                  - DOMINGO
                  - SEGUNDA_FEIRA
                  - TERCA_FEIRA
                  - QUARTA_FEIRA
                  - QUINTA_FEIRA
                  - SEXTA_FEIRA
                  - SABADO
                description: Dia da semana de abertura
              openingTime:
                type: string
                description: Horário de abertura (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$
              closingTime:
                type: string
                description: Horário de fechamento (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$
        exception:
          type: string
          maxLength: 2000
          pattern: \w*\W*
          example: Exceto feriados municipais, nacionais e estaduais
        allowPublicAccess:
          type: boolean
          example: false
    Company:
      type: object
      properties:
        name:
          type: string
          description: Nome da Instituição, pertencente à Marca.
          maxLength: 80
          pattern: \w*\W*
          example: 'Empresa da Organização A'
        urlComplementaryList:
          type: string
          pattern: \w*\W*
          maxLength: 1024
          description: |
            URL de link para lista complementar com os nomes e CNPJs agrupados para o caso instituições ofertantes de produtos e serviços com as mesmas características.
          example: 'https://empresadaorganizacaoa.com/complementarylist'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    Brand:
      type: object
      properties:
        name:
          type: string
          maxLength: 80
          pattern: \w*\W*
          description: Nome da marca selecionada pela Organização
          example: Organização A
    CNPJ:
      type: object
      properties:
        cnpjNumber:
          type: string
          pattern: '^(\d{14})$'
          description: Número completo do CNPJ da instituição
          maxLength: 14
          example: "50685362000135"
    Links:
      type: object
      properties:
        self:
          type: string
          description: URL da página atualmente requisitada
          example: "https://api.banco.com.br/open-banking/channels/v1/<resource>"
        first:
          type: string
          description: URL da primeira página de registros
          example: "https://api.banco.com.br/open-banking/channels/v1/<resource>"
        prev:
          type: string
          description: URL da página anterior de registros
        next:
          type: string
          description: URL da próxima página de registros
        last:
          type: string
          description: URL da última página de registros
          example: "https://api.banco.com.br/open-banking/channels/v1/<resource>"
    Meta:
      type: object
      properties:
        totalRecords:
          type: integer
          description: Total de registros encontrados
          example: 1
        totalPages:
          type: integer
          description: Total de páginas para os registros encontrados
          example: 1
      required:
        - totalRecords
        - totalPages

#### ATM specific schemas because of optional NA values ####
    SharedAutomatedTellerMachinesCompany:
      type: object
      properties:
        name:
          type: string
          description: Nome da Instituição, pertencente à Marca.
          maxLength: 80
          pattern: \w*\W*
          example: 'Empresa da Organização A'
        urlComplementaryList:
          type: string
          pattern: \w*\W*
          maxLength: 1024
          description: |
            URL de link para lista complementar com os nomes e CNPJs agrupados para o caso instituições ofertantes de produtos e serviços com as mesmas características.
          example: 'https://empresadaorganizacaoa.com/complementarylist'
        cnpjNumber:
          type: string
          pattern: '^(\d{14})$|^NA$'
          description: Número completo do CNPJ da instituição
          maxLength: 14
          example: "50685362000135"
    SharedAutomatedTellerMachinesAvailability:
      type: object
      properties:
        standards:
          type: array
          items:
            properties:
              weekday:
                type: string
                enum:
                  - DOMINGO
                  - SEGUNDA_FEIRA
                  - TERCA_FEIRA
                  - QUARTA_FEIRA
                  - QUINTA_FEIRA
                  - SEXTA_FEIRA
                  - SABADO
                description: Dia da semana de abertura
                example: SEGUNDA_FEIRA
              openingTime:
                type: string
                description: Horário de abertura (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$|^NA$
                example: '10:00:57Z'
              closingTime:
                type: string
                description: Horário de fechamento (UTC)
                maxLength: 13
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|Z$|^NA$
                example: '16:00:57Z'
        exception:
          type: string
          maxLength: 2000
          pattern: \w*\W*
          example: Exceto feriados municipais, nacionais e estaduais
        allowPublicAccess:
          type: boolean
          example: false
    SharedAutomatedTellerMachinesPostalAddress:
      type: object
      properties:
        address:
          type: string
          description: "Deverá trazer toda a informação referente ao endereço da dependência informada: Tipo de logradouro + Nome do logradouro + Número do Logradouro (se não existir usar ' s/n') + complemento (se houver), como, p.ex.: 'R Diamatina, 59, bloco 35, fundos' 'Praça da Boa Vontade s/n'"
          maxLength: 150
          pattern: \w*\W*
          example: 'Av Naburo Ykesaki, 1270'
        additionalInfo:
          type: string
          description: "Complemento"
          maxLength: 30
          pattern: \w*\W*
          example: 'Fundos'
        districtName:
          type: string
          description: "Bairro é uma comunidade ou região localizada em uma cidade ou município de acordo com as suas subdivisões geográficas. p.ex: 'Paraíso'"
          maxLength: 50
          pattern: \w*\W*
          example: 'Centro'
        townName:
          type: string
          description: "Localidade: O nome da localidade corresponde à designação da cidade ou município no qual o endereço está localizado. p.ex. 'São Paulo'"
          maxLength: 50
          pattern: \w*\W*
          example: 'Marília'
        ibgeCode:
          type: string
          description: "Código IBGE do município"
          maxLength: 7
          pattern: \d{7}|^NA$
          example: '3515890'
        countrySubDivision:
          type: string
          description: "Enumeração referente a cada sigla da unidade da federação que identifica o estado ou o distrito federal, no qual o endereço está localizado. p.ex. 'AC'. São consideradas apenas as siglas para os estados brasileiros"
          enum:
            - AC
            - AL
            - AP
            - AM
            - BA
            - CE
            - DF
            - ES
            - GO
            - MA
            - MT
            - MS
            - MG
            - PA
            - PB
            - PR
            - PE
            - PI
            - RJ
            - RN
            - RS
            - RO
            - RR
            - SC
            - SP
            - SE
            - TO
          example: 'SP'
        postCode:
          type: string
          description: "Código de Endereçamento Postal"
          pattern: (\d{8})|^NA$
          maxLength: 8
          example: '17500001'
        country:
          type: string
          description: "Nome do país"
          maxLength: 80
          pattern: \w*\W*
          example: 'Brasil'
        countryCode:
          type: string
          description: "Código do país"
          example: 'BRA'
        geographicCoordinates:
          $ref: '#/components/schemas/GeographicCoordinates'
